### ISSUE TITLE
Best practices for Axis Internal to leave feedback

### ISSUE THREAD

**Issue by manasvil** [axisgroup/design-process#11]
As part of the call,  I believe we should set expectations that this is WIP and that we'd love to hear their feedback/questions/concerns.

Should also give them a TL;DR version of how to leave issues on Github.

**Comment by skokenes** [comment]
FYI, we have a starting point for this here https://github.com/axisgroup/design-process/blob/master/CONTRIBUTING.md

I believe this was copied from another process, so we need to rework it to match our process and goals.

**Comment by manasvil** [comment]
Yep it's based off https://github.com/thoughtbot/design-sprint's directory structure

**Comment by skokenes** [comment]
Ok someone should take our CONTRIBUTING.md and rewrite it to reflect our repo and approach for contributing

**Comment by g-ellsworth** [comment]
Edited this https://github.com/axisgroup/design-process/blob/master/CONTRIBUTING.md
Need review.

**Comment by skokenes** [comment]
the word "sprint" should be replaced with engagements throughout. Also, are we collecting case study info here? 

Also, there is stuff here from the previous document, like suggesting people do rebasing on their commits, etc. Idk if we want to go to that level of detail. If they want to contribute, isn't it as simple as saying fork the repo, make your changes in a branch, then make a pull request and we'll review?

**Comment by g-ellsworth** [comment]
Removed rebasing stuff. restructured into 2 ways to contribute: Issues, and Make Changes in Your Branch.
Need to discuss if we should collect case study here. Currently there isn't case study in this document.

**Comment by g-ellsworth** [comment]
Not collecting case study here.
