### ISSUE TITLE
Timeframe suggestion misleading?

### ISSUE THREAD

**Issue by skokenes** [axisgroup/design-process#13]
On the home README, it says:

> The Design process at Axis Group is divided into six phases, Understand, Define, Diverge, Decide, Prototype, and Validate. **Each phase typically lasts for a day or two**, depending on the scope of the engagement.

I think we should remove this. That is not true, it varies wildly from project to project and this implies that every design engagement should be between 1 to 2 weeks, which is not normal for us.

**Comment by g-ellsworth** [comment]
Removed that sentence.

**Comment by g-ellsworth** [comment]
Timeframe removed

**Comment by g-ellsworth** [comment]
Timeframe removed
