### ISSUE TITLE
Standardize language

### ISSUE THREAD

**Issue by skokenes** [axisgroup/design-process#14]
Our terminology changes from phase to phase in the current docs.

Example:
Phase 1 - The methods are referred to as "Techniques"
Phase 2 - The methods are referred to as "Methods/Techniques"
Phase 3/4 - The methods are referred to as "Tasks and Activities"

Let's just user the term "Methods" and standardize across all phases

**Comment by g-ellsworth** [comment]
Changed to "Methods" in all phases.
