### ISSUE TITLE
output language on Phase 0 needs cleanup

### ISSUE THREAD

**Issue by skokenes** [axisgroup/design-process#15]
> Outputs/Artifacts:
> 
> Capture Industry and Client Research: The team should document research outcomes as they would be useful in future phases to ensure that the team has common grounds for formulating assumptions and identifying risks. Capturing research shall also serve as a repository for any similar sprints in future.
> 
> A list of roles that will be involved in the project.
> 
> Requests to Schedule Interviews/ Request for Information: The team should identify resources and key stakeholders from the client-side and send out requests to schedule interviews, and request for additional material/information. This ensures that the client is prepared with information that the design team might require to better understand the problem at hand.

The artifacts here sound like methods rather than an output. "Capturing Research" isn't an output. Notes that summarize the research are. So outputs should be physical things. Likewise, I would think an output is "Interview Schedule", not request for interview.

**Comment by g-ellsworth** [comment]
I'm cleaning up this Readme right now. Lisa is cleaning up the main Readme. I think all the Readmes in the phases need cleaning up / re-writing. Some of initial writing isn't accurate.

**Comment by g-ellsworth** [comment]
All phase READMEs are cleaned up by Liza.
