### ISSUE TITLE
phase checklists are missing

### ISSUE THREAD

**Issue by skokenes** [axisgroup/design-process#16]
There are no links to the phase checklists anywhere that I can find

**Comment by skokenes** [comment]
Nevermind I see them now, it wasn't obvious to me to click there. I'm wondering if it just makes more sense to have it on the Phase README. worth discussing.

**Comment by g-ellsworth** [comment]
It is in the main folder called "Design Process Checklist". and in each phase, you can click on the Phase Checklist link.

**Comment by g-ellsworth** [comment]
In the phase Readme there is a phase checklist, but I thought it'd be useful to have link to a full checklist.

**Comment by liza92** [comment]
Added the checklist to the read me document for each phase with a link to the full checklist
