### ISSUE TITLE
User Stories / User Flows

### ISSUE THREAD

**Issue by skokenes** [axisgroup/design-process#2]
Discussed with @jessielian about doing more with user stories / user flows. Those methods could be built out more in the Define phase. Does this fit with the User Scenarios method, or is it different?

**Comment by g-ellsworth** [comment]
To me user stories sound similar to user scenarios. Task Analysis can generate a flow chart for a user. There's another method called User Journey, which also draws out a flow chart. To me these two methods are similar, so I kind of combined them. But we can add User Journey as a separate method, and everyone can choose whichever they want to use.

**Comment by skokenes** [comment]
Ok maybe getting into the weeds on semantics here, are there any distinctions between:
* User Story
* User Flow
* User Journey
* User Scenario

?

**Comment by manasvil** [comment]
Can we close this now @g-ellsworth

**Comment by skokenes** [comment]
I'd say close it when @g-ellsworth provides a link to his presentation / incorporates it somehow back into this repo, maybe as part of FAQ.

Also this issue has kind of split into two separate things. Originally, it was about @jessielian's idea that we add more methods in about user *'s. Then it transitioned into an issue about distinguishing between the different user *s.

I think we've resolved issue 2 but not issue 1. Maybe it makes sense for @jessielian to open a new issue around the implementation of more user * methods.

**Comment by g-ellsworth** [comment]
Added question and presentation in FAQ section.
All these methods are now in this documentation, which should resolve issue 1. Or are there other user* methods we want to add?

**Comment by g-ellsworth** [comment]
All 7 user* methods included in the process. explanation attached to FAQ
