### ISSUE TITLE
Run on formatting

### ISSUE THREAD

**Issue by skokenes** [axisgroup/design-process#21]
There are several places where we have poor formatting like so:

> Outputs/Artifacts:
> 
> Rough Sketches of Ideas Each team member should organize their ideas on either paper, whiteboard, or Sketch -- whatever works best for sharing and discussion.

In this situation, "Rough Sketches of Ideas" is not separated from the next sentence. Need someone to go through the text and correct these types of issues.

Also for inputs and outputs, I wonder if it would be better to bold the title of each artifact so that it stands out more from the description

**Comment by liza92** [comment]
Made the titles for each artifact bold and went through the formatting.
