### ISSUE TITLE
Method descriptions are incomplete

### ISSUE THREAD

**Issue by skokenes** [axisgroup/design-process#22]
Many of the method descriptions are incomplete. We need to approach them from the perspective of someone who has never done them. Is there enough information on each description to understand:

- What is the method?
- When do you do it?
- Why would you do it?
- How do you do it?

Take the 3 minute critique for example. All the method documentation says is:

> Three minute critiques is another group critique exercise. The group gather around the concepts and spend 3 minutes discussing each concept. Instead of explaining the concepts, the group start by making comments on the concepts they like first. Then ask the author if there's anything to add.
> 
> This exercise could be combined with the silent critiques and the group can start with the concept that got most stickers on it.

It's confusing right off the bat because it references a different method completely. So it isn't self-sufficient. Just reading this description, I do not understand how to lead this 3 minute critique method with a team.

**Comment by g-ellsworth** [comment]
Added What, Why, When and How to all the method descriptions.
