### ISSUE TITLE
FAQ is incomplete

### ISSUE THREAD

**Issue by skokenes** [axisgroup/design-process#26]
In general, I find the FAQ hard to understand. There isn't a lot of information, the questions are worded poorly, and the responses don't go into enough detail. 

At all times when creating this manual, please consider the perspective of someone who has no background with the design team and whether the content would make sense to them or not.

**Comment by g-ellsworth** [comment]
Rephrased question 1, expanded answer. Moved question 2 & 3 to Resources folder.
