### ISSUE TITLE
"Methods" instead of "Exercises"?

### ISSUE THREAD

**Issue by skokenes** [axisgroup/design-process#3]
This is nitpicky, but I wonder if "Method" is a better word than "Exercise". It feels like it more accurately reflects the nature of our activities.

**Comment by skokenes** [comment]
When closing issues in the future, please include a comment describing the resolution. So in this case, the closing comment would be "Updated the terminology to say Methods"

**Comment by g-ellsworth** [comment]
Updated the terminology to say Methods
