### ISSUE TITLE
Modify Understand phase to encompass more stages

### ISSUE THREAD

**Issue by manasvil** [axisgroup/design-process#34]
Restructure methods to have the following hierarchy:
Understand the Business

- SME Interviews
- Desk Research
- Business Model Survey

Understand the People

- Stakeholder Interview
- User Interviews
- 1 on 1
- Focus Groups -- Affinity Mapping
- Observation
- Survey

[Understand the Data
](https://github.com/axisgroup/design-process/issues/35)

**Comment by jessielian** [comment]
Restructured Understand readme to include business, people, and data. Updated to include SME interviews, desk research, and business model survey. Consequently, deleted the "pre-engagement" phase. Note: We still need to discuss and create methods Focus Groups and Survey.
